version: 2
updates:
  # Python dependencies (pyproject.toml)
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    groups:
      dev-dependencies:
        patterns:
          - "ruff"
          - "pytest*"
          - "pyright*"
          - "pre-commit"
    commit-message:
      prefix: "[misc] chore:"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "[ci] chore:"
    labels:
      - "dependencies"
      - "ci"
