changelog:
  categories:
    - title: "\u26a0\ufe0f Breaking Changes"
      labels:
        - breaking
    - title: "\ud83d\ude80 Features"
      labels:
        - enhancement
    - title: "\ud83d\udc1b Bug Fixes"
      labels:
        - bug
    - title: "\ud83d\udcd6 Documentation"
      labels:
        - documentation
    - title: "\ud83d\udd27 Maintenance"
      labels:
        - chore
        - ci
        - dependencies
        - refactor
