name: Bug Report
description: Report a bug in osmosis-ai SDK
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill in the details below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Install osmosis-ai with `pip install osmosis-ai`
        2. Run the following code:
        ```python
        from osmosis_ai import ...
        ```
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include full error messages or tracebacks if applicable.
    validations:
      required: true

  - type: input
    id: sdk-version
    attributes:
      label: SDK Version
      description: "Output of `pip show osmosis-ai | grep Version` or `osmosis --version`"
      placeholder: "e.g. 0.5.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: "Output of `python --version`"
      placeholder: "e.g. 3.12.3"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "e.g. Ubuntu 22.04 / macOS 14.5 / Windows 11"
    validations:
      required: false

  - type: dropdown
    id: install-method
    attributes:
      label: Installation Method
      options:
        - pip install osmosis-ai
        - pip install -e . (editable)
        - uv sync
        - Other
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, logs, or screenshots.
    validations:
      required: false
